[package]
name = "scene_create"
version = "0.1.0"
authors = ["The godot-rust developers"]
publish = false
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { path = "../../gdnative" }
euclid = "0.20.1"
