[package]
name = "gdnative_bindings_generator"
description = "Generates bindings for the Godot engine's gdnative classes from a json api description file."
repository = "https://github.com/GodotNativeTools/godot-rust"
license = "MIT"
version = "0.7.0"
authors = ["The godot-rust developers"]
edition = "2018"

[dependencies]
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"
heck = "0.3.0"
