[package]
name = "gdnative-core"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative core bindings."
documentation = "https://docs.rs/crate/gdnative-core"
repository = "https://github.com/godot-rust/godot-rust"
homepage = "https://godot-rust.github.io/"
version = "0.9.3"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
default = ["nativescript"]
gd_test = []
nativescript = ["bitflags", "parking_lot"]
type_tag_fallback = []

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.9.3" }
gdnative-impl-proc-macros = { path = "../impl/proc_macros", version = "=0.9.3" }
ahash = "=0.7.4" # TODO use flexible version as soon as https://github.com/tkaitchuck/aHash/issues/99 is fixed
approx = "0.5.0"
atomic-take = "1.0.0"
bitflags = { version = "1.2.1", optional = true }
glam = "0.19.0"
indexmap = "1.7.0"
libc = "0.2.98"
once_cell = "1.8.0"
parking_lot = { version = "0.11.1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
gdnative = { path = "../gdnative", version = "0.9.3" } # for doc-tests