[package]
name = "gdnative-core"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative core bindings."
documentation = "https://docs.rs/crate/gdnative-core"
repository = "https://github.com/godot-rust/godot-rust"
homepage = "https://godot-rust.github.io/"
version = "0.9.3"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
default = ["nativescript"]
gd_test = []
nativescript = ["bitflags", "parking_lot"]
type_tag_fallback = []

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.9.3" }
gdnative-impl-proc-macros = { path = "../impl/proc_macros", version = "=0.9.3" }
ahash = "0.7.6"
approx = "0.5.0"
atomic-take = "1.0.0"
bitflags = { version = "1.3.2", optional = true }
glam = "0.19.0"
indexmap = "1.7.0"
libc = "0.2.104"
once_cell = "1.8.0"
parking_lot = { version = "0.11.2", optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }

[dev-dependencies]
gdnative = { path = "../gdnative", version = "0.9.3" } # for doc-tests
