name: Publish to crates.io

on:
  push:
    branches:
      - '!**'
    tags:
      - '0.9.[0-9]+'
      - '0.10.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Sanity tests
        run: |
          cargo fmt --all -- --check;
          cargo clippy --all --all-features -- -D clippy::style -D clippy::complexity -D clippy::perf -D clippy::dbg_macro -D clippy::todo -D clippy::unimplemented;
          cargo test --all --all-features;
      - name: Publishing to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: |
          (cd impl/proc_macros && cargo publish);
          sleep 1m;
          (cd gdnative-sys && cargo publish);
          sleep 1m;
          (cd gdnative-derive && cargo publish);
          sleep 1m;
          (cd gdnative-core && cargo publish);
          sleep 1m;
          (cd bindings_generator && cargo publish);
          sleep 1m;
          (cd gdnative-bindings && cargo publish);
          sleep 1m;
          (cd gdnative && cargo publish);